Revert "Use cstdint types in integral_types.h"
This reverts commit 101ae83c4c880e41434f4b812eb19bd1a706b4e9.

This unbreaks pywraps2_test in Travis CI's configuration.
https://travis-ci.org/google/s2geometry/jobs/460894006

======================================================================
ERROR: testS2CellDistance (__main__.PyWrapS2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/google/s2geometry/src/python/pywraps2_test.py", line 213, in testS2CellDistance
    cell = s2.S2Cell(s2.S2CellId(0x1000000000000000))
  File "/home/travis/build/google/s2geometry/build/python/pywraps2.py", line 311, in __init__
    this = _pywraps2.new_S2CellId(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_S2CellId'.
  Possible C/C++ prototypes are:
    S2CellId::S2CellId(uint64)
    S2CellId::S2CellId(S2Point const &)
    S2CellId::S2CellId(S2LatLng const &)
    S2CellId::S2CellId()

Possibly related to different SWIG or stdint.i versions.  It looks like
the uint64 -> uint64_t mapping is not being found.

It worked when I tested.