GetCommonAncestorLevel: work around bit_width return type bug (#431)
`absl::bit_width<uint64_t>()` returns `uint64_t`, not `int` for old
libstdc++ versions (such as gcc <= 12) with `-std=c++20`.

This breaks overload resolution for `std::max`.

```
error: no matching function for call to 'max'
[build]   return max(61 - absl::bit_width(bits), -1) >> 1;
[build]          ^~~
[build] /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/algorithmfwd.h:407:5: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('unsigned long' vs. 'int')
```

System: Debian 12
Compiler: Clang-15

Work around with an explicit cast.  This can be removed when we depend on
an abseil-cpp LTS that fixes
https://github.com/abseil/abseil-cpp/issues/1890.