Fix error: use of undeclared identifier 'ABSL_INTERNAL_ASSUME' (#238)
`ABSL_INTERNAL_ASSUME` was replaced by `ABSL_ASSUME` in
https://github.com/abseil/abseil-cpp/commit/231c393a170ce3c6d83e8456bc87fe917c333ecf.

Define `S2_ASSUME` to either `ABSL_ASSUME` or `ABSL_INTERNAL_ASSUME`, depending on what's available. The latest LTS release does not yet have `S2_ASSUME`.

Fixes #237